config/routes.rb
Rails.application.routes.draw do
  devise_for :professors
  devise_for :students

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :professors do
      resources :professors
      resources :students
      get "home/index"
      root "home#index"
    end
    resources :answers
    resources :questions
    resources :quizzes do
      patch "toggle_quiz", on: :member
    end
    resources :groups
    resources :semesters
    resources :attempts
    resources :courses

    root "home#index"
  end

  # read-only API
  resources :reports, only: [:index, :show] do
    get "by_groups", on: :member
    get "by_students", on: :member
  end

  # professors namespace root shortcut
  get "/pro", to: "professors/home#index"

  # fallback to root if locale param is missing
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  # mount ActionCable.server => "/cable"
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id                  :integer          not null, primary key
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  professor_id        :integer
#  group_id            :integer
#  name                :string
#  courses_semester_id :integer
#

class Group < ApplicationRecord
  # default_scope { order(created_at: :desc) } # newest_first # breaks globalize gem.
  # translates :name, fallbacks_for_empty_translations: true

  belongs_to :courses_semester
  belongs_to :professor
  has_many :groups_students, dependent: :destroy
  has_many :students, through: :groups_students

  has_many :quizzes, dependent: :destroy

  has_many :quiz_permutations

  validates :group_id, presence: true, uniqueness: true, numericality: { only_integer: true }

  before_save :set_group_name

  def set_group_name
    self.name = "#{professor.name} | #{courses_semester.courses_semester_name_concat}"
  end
end

app/controllers/groups_controller.rb
class GroupsController < Professors::ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /group
  def index
    @groups = Group.all.page(params[:page]).per(25)
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.professor_id = current_professor.id

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :group_id, :courses_semester_id, student_ids: [])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group, html: { class: "form-horizontal", role: "form" } do |f|
  -if @group.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= t("errors.template.header", count: @group.errors.count, model: Group.model_name.human)

      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label t(:group_id), class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :group_id, class: "form-control"
  .form-group
    = f.label t(:name), class: "col-sm-2 control-label"
    .col-sm-10
      = @group.name if @group.name.present?
  -# .form-group
  -#   = f.label t(:semester), class: "col-sm-2 control-label"
  -#   .col-sm-10
  -#     = f.collection_select(:semester_id, Semester.all, :id, :semester_name_concat, {include_hidden: true}, { class: "form-control" })
  .form-group
    = f.label t(:belongs_to_course_semester), class: "col-sm-2 control-label"
    .col-sm-10
      = f.collection_select(:courses_semester_id, CoursesSemester.all, :id, :courses_semester_name_concat, {include_hidden: true}, { class: "form-control" })
  .form-group
    = f.label t(:professor), class: "col-sm-2 control-label"
    .col-sm-10
      = current_professor.name
  .form-group
    = f.label t(:students), class: "col-sm-2 control-label"
    .col-sm-10
      = f.collection_select(:student_ids, Student.all, :id, :student_name_concat,
      {include_hidden: true}, { id: "include_students_in_group", class: "form-control", multiple: true })
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/groups/edit.html.haml
.page-header
  = link_to groups_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    =t(:back)
  &nbsp
  = link_to @group, class: "btn btn-primary" do
    %span.glyphicon.glyphicon-info-sign
    =t(:show)
  %h1=t(:editing_group)

= render "form"

app/views/groups/index.html.haml
.page-header
  = link_to new_group_path, class: "btn btn-primary #{can_class(:create, Group)}" do
    %span.glyphicon.glyphicon-plus
    =t(:new_group)
  %h1=t(:listing_groups)

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th.col-sm-2=t(:group_id)
        %th.col-sm-7=t(:name)
        %th.col-sm-1
        %th.col-sm-1
        %th.col-sm-1

    %tbody
      - @groups.each do |group|
        %tr
          %td= group.group_id
          %td= group.name
          %td= link_to t(:show), group, class: "btn btn-primary #{can_class(:show, group)}"
          %td= link_to t(:edit), edit_group_path(group), class: "btn btn-warning #{can_class(:update, group)}"
          %td= link_to t(:destroy), group, data: { confirm: t(:are_you_sure) }, method: :delete, class: "btn btn-danger #{can_class(:destroy, group)}"

= paginate @groups

app/views/groups/new.html.haml
.page-header
  = link_to groups_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    =t(:back)
  %h1=t(:new_group)

= render "form"

app/views/groups/show.html.haml
.page-header
  = link_to groups_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    =t(:back)
  &nbsp
  = link_to edit_group_path(@group), class: "btn btn-primary #{can_class(:update, @group)}" do
    %span.glyphicon.glyphicon-pencil
    =t(:edit)
  %h1=t(:show_group)

%dl.dl-horizontal
  %dt=t(:group_id)
  %dd= @group.group_id
  %dt=t(:name)
  %dd= @group.name
  %dt=t(:course_and_semester)
  %dd= @group.courses_semester.courses_semester_name_concat
  %dt=t(:professor)
  %dd= @group.professor.name
  %br
  %dt=t(:students)
  %dd
    .table-responsive
      %table.table.table-hover
        %thead
          %tr
            %th.col-sm-2= t(:student_id)
            %th.col-sm-10= t(:student_name)
        %tbody
          -@group.students.each do |student|
            %tr
              %td= student.student_id
              %td
                - if can? :show, student
                  =link_to student.name, professors_student_path(student)
                - else
                  = student.name