config/routes.rb
Rails.application.routes.draw do
  devise_for :professors
  devise_for :students

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :professors do
      resources :professors
      resources :students
      get "home/index"
      root "home#index"
    end
    resources :answers
    resources :questions
    resources :quizzes do
      patch "toggle_quiz", on: :member
    end
    resources :groups
    resources :semesters
    resources :attempts
    resources :courses

    root "home#index"
  end

  # read-only API
  resources :reports, only: [:index, :show] do
    get "by_groups", on: :member
    get "by_students", on: :member
  end

  # professors namespace root shortcut
  get "/pro", to: "professors/home#index"

  # fallback to root if locale param is missing
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  # mount ActionCable.server => "/cable"
end

app/models/attempt.rb
# == Schema Information
#
# Table name: attempts
#
#  id                  :integer          not null, primary key
#  student_id          :integer
#  score               :float
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  quiz_permutation_id :integer
#  completed           :boolean          default(FALSE)
#

class Attempt < ApplicationRecord
  default_scope { order(created_at: :desc) } # newest_first
  belongs_to :student
  belongs_to :quiz_permutation
  has_many :responses, dependent: :destroy

  accepts_nested_attributes_for :responses, update_only: true
  before_save :attempt_score_setter

  def attempt_score_setter
    self.score = responses.select(&:correct).map(&:question).map(&:question_category).sum(&:weight)
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :set_attempt, only: [:edit, :update]
  load_and_authorize_resource

  def index
    @attempts = current_student.attempts & Quiz.active.map(&:attempts).flatten
  end

  def edit
    completed_quiz_fallback if @attempt.completed?
  end

  def update
    # cleaning rails checkbox automagics
    params[:attempt][:responses_attributes].delete_if { |_key, value| value.is_a?(Hash) }

    params[:attempt][:responses_attributes] =
      params[:attempt][:responses_attributes].map do |key, value|
        { question_id: key, answer_ids: value }
      end

    if @attempt.update(attempt_params)
      @attempt.update_attributes(completed: true)
      redirect_to attempts_path, notice: I18n.t(:quiz_successfully_submitted)
    else
      render :edit
    end
  end

  private

    def completed_quiz_fallback
      redirect_to attempts_path, notice: I18n.t(:quiz_already_completed)
    end

    def set_attempt
      @attempt = Attempt.find(params[:id])
      redirect_to attempts_path, notice: I18n.t(:quiz_expired) unless @attempt.quiz_permutation.quiz.active?
    end

    def attempt_params
      params.require(:attempt).permit(
        :student_id,
        responses_attributes: [:id, :question_id, :correct, :answer_ids, answer_ids: []]
      )
    end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/views/attempts/_form.html.haml
= form_for @attempt, html: { class: "form-horizontal", role: "form" } do |f|
  -if @attempt.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= t("errors.template.header", count: @attempt.errors.count, model: Quiz.model_name.human)

      %ul
        - @attempt.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :student_id, value: current_student.id
  = f.fields_for :responses, @attempt.quiz_permutation.question_permutations.shuffle do |question_permutation|
    - question = question_permutation.object.question
    %li.attempt-question= "(#{question.question_category.weight} ქულა) - #{question.content}"
    .attempt-question
      -if question.radio?
        = collection_radio_buttons("attempt[responses_attributes]", question.id, question.answers.shuffle, :id, :content) do |b|
          .attempt-question
            = b.label { "#{b.radio_button} #{b.text}" }
      -else
        = collection_check_boxes("attempt[responses_attributes]", question.id, question.answers.shuffle, :id, :content) do |b|
          .attempt-question
            = b.label { "#{b.check_box} #{b.text}" }
  %br
  = f.submit class: "btn btn-primary"

app/views/attempts/edit.html.haml
.page-header
  = link_to attempts_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    =t(:back)
  %h1=t(:taking_quiz)

%button.btn.btn-warning{"data-target": "#countdown", "data-toggle": "collapse", type: "button"}=t(:show_timer)
%br
%br
#countdown.collapse
%br

= render "form"

-time_left = (@attempt.quiz_permutation.quiz.expires_at - Time.current).to_i
:javascript

    function submitFormAndRedirect(){
      $("form").submit();
    }

    $(document).ready( function() {
      $("#countdown").countdown({until: "#{time_left}",
        compact: true,
        format: "MS",
        description: "<i>#{I18n.t(:quiz_will_autosubmit_when_time_expires)}</i>",
        onExpiry: submitFormAndRedirect,
        expiryUrl: "#{attempts_url(I18n.default_locale)}"
      });
    });

app/views/attempts/index.html.haml
.page-header
  %h1=t(:listing_attempts)

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t(:group_name)
        %th= t(:completed)
        %th

    %tbody
      - @attempts.each do |attempt|
        %tr
          %td= attempt.quiz_permutation.group.name
          %td= raw attempt.completed? ? "&#x2713;" : "&#x2717;"
          %td= link_to t(:take_quiz), edit_attempt_path(attempt)