config/routes.rb
Rails.application.routes.draw do
  devise_for :professors
  devise_for :students

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :professors do
      resources :professors
      resources :students
      get "home/index"
      root "home#index"
    end
    resources :answers
    resources :questions
    resources :quizzes do
      patch "toggle_quiz", on: :member
    end
    resources :groups
    resources :semesters
    resources :attempts
    resources :courses

    root "home#index"
  end

  # read-only API
  resources :reports, only: [:index, :show] do
    get "by_groups", on: :member
    get "by_students", on: :member
  end

  # professors namespace root shortcut
  get "/pro", to: "professors/home#index"

  # fallback to root if locale param is missing
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  # mount ActionCable.server => "/cable"
end

app/models/professor.rb
# == Schema Information
#
# Table name: professors
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  professor_id           :integer
#  admin                  :boolean          default(FALSE)
#

class Professor < ApplicationRecord
  translates :name, fallbacks_for_empty_translations: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :groups
  has_many :quizzes, through: :groups

  validates :professor_id, presence: true, uniqueness: true

  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/controllers/professors/application_controller.rb
class Professors::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout "application"
  before_action :authenticate_professor!
  before_action :set_locale
  include DeviseCustomParams

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_back fallback_location: professors_root_path, alert: exception.message
  end

  def current_ability
    @current_ability ||= professor_signed_in? ? Ability.new(current_professor) : Ability.new(current_student)
  end
end

app/controllers/professors/home_controller.rb
class Professors::HomeController < Professors::ApplicationController
  def index
    @attempts = current_professor.admin? ? Attempt.all : Attempt.where(group_id: current_professor.groups)
    @attempts = @attempts.page(params[:page]).per(25)
  end
end

app/controllers/professors/professors_controller.rb
class Professors::ProfessorsController < Professors::ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  before_action :clean_password_params, only: [:update]
  load_and_authorize_resource

  def index
    @professors = Professor.where.not(id: current_professor.id).page(params[:page]).per(25)
  end

  def show
  end

  def new
    @professor = Professor.new
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)

    if @professor.save
      redirect_to professors_professor_path(@professor), notice: 'Professor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @professor.update(professor_params)
      redirect_to professors_professor_path(@professor), notice: 'Professor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @professor.destroy
    redirect_to professors_professors_url, notice: 'Professor was successfully destroyed.'
  end

  private

  def clean_password_params
    if params[:professor][:password].blank? &&
       params[:professor][:password_confirmation].blank?
      params[:professor].delete(:password)
      params[:professor].delete(:password_confirmation)
    end
  end

  def set_professor
    @professor = Professor.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def professor_params
    params.require(:professor).permit(:name, :professor_id, :email, :admin, :password, :password_confirmation)
  end
end

app/controllers/professors/students_controller.rb
class Professors::StudentsController < Professors::ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all.page(params[:page]).per(25)
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to professors_student_path(@student), notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def update
    params[:student].delete(:password) if params[:student][:password].blank?
    if @student.update(student_params)
      redirect_to professors_student_path(@student), notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to professors_students_url, notice: 'Student was successfully destroyed.'
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :student_id, :email, :password)
  end
end

app/helpers/professors/application_helper.rb
module Professors::ApplicationHelper
end

app/helpers/professors/home_helper.rb
module Professors::HomeHelper
end

app/helpers/professors/professors_helper.rb
module Professors::ProfessorsHelper
end

app/helpers/professors/students_helper.rb
module Professors::StudentsHelper
end

app/views/professors/professors/_form.html.haml
= form_for [:professors, @professor], html: { class: "form-horizontal", role: "form" } do |f|
  -if @professor.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= t("errors.template.header", count: @professor.errors.count, model: Professor.model_name.human)

      %ul
        - @professor.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label t(:name), class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    = f.label t(:professor_id), class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :professor_id, class: "form-control"
  .form-group
    = f.label t(:email), class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :email, class: "form-control"
  .form-group
    = f.label t(:admin), class: "col-sm-2 control-label"
    -if current_professor.id == f.object.id
      .col-sm-10
        = f.label :label, "#{current_professor.admin? ? "Admin Professor" : "Professor"}" , class: "control-label"
    -else
      .btn-group{"data-toggle" => "buttons", class: "correct-switch"}
        %label{class: "btn btn-danger #{"active" if f.object.admin} #{"disabled" if current_professor.id == f.object.id}"}
          = f.check_box :admin
          =t(:admin)

  .form-group
    = f.label t(:new_password), class: "col-sm-2 control-label"
    .col-sm-10= f.text_field :password, type: :password, placeholder: :optional , class: "form-control"
  .form-group
    = f.label t(:new_password_confirmation), class: "col-sm-2 control-label"
    .col-sm-10= f.text_field :password_confirmation, type: :password, placeholder: :optional, class: "form-control"

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/professors/professors/edit.html.haml
.page-header
  = link_to professors_professors_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    =t(:back)
  &nbsp;
  = link_to professors_professor_path(@professor), class: "btn btn-primary" do
    %span.glyphicon.glyphicon-info-sign
    =t(:show)
  %h1= t(:editing_professor)

= render "form"

app/views/professors/professors/index.html.haml
.page-header
  = link_to new_professors_professor_path, class: "btn btn-primary #{can_class(:create, Professor)}" do
    %span.glyphicon.glyphicon-plus
    = t(:new_professor)
  %h1= t(:professor_index)

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t(:name)
        %th= t(:professor_id)
        %th= t(:email)
        %th.col-sm-1= "#{t(:admin)}?"
        %th.col-sm-1
        %th.col-sm-1
        %th.col-sm-1

    %tbody
      - @professors.each do |professor|
        %tr
          %td= professor.name
          %td= professor.professor_id
          %td= professor.email
          %td.col-sm-1
            = professor.admin ? "\u2713" : "\u2717"
          %td.col-sm-1= link_to t(:show), professors_professor_path(professor), class: "btn btn-primary #{can_class(:show, professor)}"
          %td.col-sm-1= link_to t(:edit), edit_professors_professor_path(professor), class: "btn btn-warning #{can_class(:update, professor)}"
          %td.col-sm-1= link_to t(:destroy), professors_professor_path(professor), data: { confirm: t(:are_you_sure) }, method: :delete, class: "btn btn-danger #{can_class(:destroy, professor)}"

= paginate @professors

app/views/professors/professors/new.html.haml
.page-header
  = link_to professors_professors_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    =t(:back)
  %h1=t(:new_professor)

= render "form"

app/views/professors/professors/show.html.haml
.page-header
  = link_to professors_professors_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    =t(:back)
  &nbsp;
  = link_to edit_professors_professor_path(@professor), class: "btn btn-primary #{can_class(:update, @professor)}" do
    %span.glyphicon.glyphicon-pencil
    =t(:edit)
  %h1= t(:show_professor)

%dl.dl-horizontal
  %dt=t(:name)
  %dd= @professor.name
  %dt=t(:professor)
  %dd= @professor.professor_id
  %dt=t(:email)
  %dd= @professor.email
  %dt="#{t(:admin)}?"
  %dd= @professor.admin ? "\u2713" : "\u2717"